import { ComponentIndex } from '../../services/componentIndex.js';
import { AngularParser } from '../../parsers/angularParser.js';

export async function syncToFigma(args: {
  selector: string;
  targetFileKey: string;
  targetPageId?: string;
}) {
  const index = new ComponentIndex();
  const rec = index.getBySelector(args.selector);
  if (!rec) throw new Error(`Component not found: ${args.selector}`);

  const parser = new AngularParser();
  const sourcePath = process.env.ANGULAR_SOURCE_PATH || '.';
  const syncModel = parser.parseComponentForSync(args.selector, sourcePath);

  // Generate Figma Plugin script
  const script = generateFigmaPluginScript(args.selector, args.targetFileKey, args.targetPageId, rec);

  return {
    selector: args.selector,
    targetFileKey: args.targetFileKey,
    pluginScript: script,
    instructions: [
      '1. Open Figma and navigate to your file',
      '2. Go to Plugins → Development → Open Console',
      '3. Paste the script below into the console and press Enter',
      '4. The component frame will be created on the current page',
    ].join('\n'),
  };
}

function generateFigmaPluginScript(
  selector: string,
  fileKey: string,
  pageId: string | undefined,
  rec: { inputs: Array<{ name: string; type: string; defaultValue?: string }> }
): string {
  const frameName = selector.replace(/^app-/, '').replace(/-/g, ' ')
    .split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  const inputDocs = rec.inputs.slice(0, 5)
    .map(i => `//   ${i.name}: ${i.type}${i.defaultValue ? ` = ${i.defaultValue}` : ''}`)
    .join('\n');

  return `// Figma Plugin Script — Generated by figma-angular-mcp
// Component: ${selector}
// File: ${fileKey}
${pageId ? `// Target Page: ${pageId}` : ''}

(function() {
  // Component API:
${inputDocs}

  const frame = figma.createFrame();
  frame.name = '${frameName}';
  frame.layoutMode = 'VERTICAL';
  frame.primaryAxisSizingMode = 'AUTO';
  frame.counterAxisSizingMode = 'AUTO';
  frame.paddingTop = 16;
  frame.paddingBottom = 16;
  frame.paddingLeft = 16;
  frame.paddingRight = 16;
  frame.itemSpacing = 8;
  frame.cornerRadius = 4;
  frame.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];

  // Add title text
  const title = figma.createText();
  figma.loadFontAsync({ family: 'Inter', style: 'Bold' }).then(() => {
    title.fontName = { family: 'Inter', style: 'Bold' };
    title.characters = '${frameName}';
    title.fontSize = 16;
    frame.appendChild(title);

    // Add to current page
    figma.currentPage.appendChild(frame);
    frame.x = figma.viewport.center.x - frame.width / 2;
    frame.y = figma.viewport.center.y - frame.height / 2;
    figma.viewport.scrollAndZoomIntoView([frame]);
    figma.notify('Component "${frameName}" created!');
  });
})();`;
}
